base_url=https://the-internet.herokuapp.com/
browser=chrome

valid_username=tomsmith
valid_password=SuperSecretPassword!
invalid_username=wrong
invalid_password=wrong

expected_secure_message=You logged into a secure area!
expected_error_login_message=Your username is invalid!